### ISSUE TITLE
I have Re-installed python and installed properly I know how to do that

### ISSUE THREAD

**Issue by sunny9t1** [Jules-WinnfieldX/CyberDropDownloader#100]
**Describe the bug**
Why were you so eager to close the request in my previous request i have clearly mentioned that i have added path noow i have reinstalled i have done everything you asked its still not working and please consider solving the issue first if someone is facing trouble rather than just type and close

**Comment by Jules-WinnfieldX** [comment]
Because this isn't an issue with my program, this is an issue with your computer and python installation/path variables. I can't control your computer, nor can I fix it for you. 

If you are pip installing using the --user flag, consider pip installing without it. I'm quite frankly tired of git issue bug requests that aren't bugs at all but are simply end user installation issues. I've given you my recommendations on solving your issue, this isn't a bug.
