### ISSUE TITLE
duplicate downloads

### ISSUE THREAD

**Issue by nocoel** [Jules-WinnfieldX/CyberDropDownloader#135]
after updating to cyberdrop-dl 2.20.1
when re-downloading a thread to download missing parts, the program re-downloads everything and makes duplicates.
this wasn't happening before updating cyberdrop-dl

**Comment by duframe** [comment]
the problem is that in previous version, in table downloads column has name **direct_url** but in new it's **path**. Renaming the column solved the problem.

**Comment by duframe** [comment]
I used to V2 and it appends new or missed files, after I switched to V3 it ignores existing files and though starts creating duplicates. When I've compared history db in V2 and V3, I copied db of V2 into V3 folder and renamed then column in the table.
And I've noticed that fresh V3 doesn't download all files from album where more then 1000 files even after several re-runs.

**Comment by Jules-WinnfieldX** [comment]
I'm not going to lie. I have no idea what you are saying. The latest version doesn't download duplicates if the files exist. But with the latest version we wiped download history because the schema isn't compatible, nor is the data inside capable of being swapped over. But if whatever you did works for you, great. But I wouldn't be surprised if it causes other problems. I wiped previous history for a reason
