### ISSUE TITLE
[BUG] Not downloading all files. 

### ISSUE THREAD

**Issue by duframe** [Jules-WinnfieldX/CyberDropDownloader#136]
V3 doesn't download all files from album where more then 1000 files even after several re-runs. On the next run a link ignores in URLs file.

**Comment by Jules-WinnfieldX** [comment]
I'm still not sure what you are referring to as V3. 

To do anything about this though I'd need to see your downloader.log file after trying said links as the issue template stated.

**Comment by nocoel** [comment]
not sure if this issue is related to what i'm experiencing but here is what's been happening with cyberdrop-dl 2.20.5

when re-running the program used to be neaty when checking existing file, now it became much messier, which results spam in the command prompt on big threads and eventually it stops and doesn't finish the thread

this screenshot is how it used to check existing files (this screenshot was taken with 2.20.5 it sometimes works fine but most of the times not): https://imgur.com/a/1ks073c

and this is how it became messy and eventually gets stuck and stops: https://imgur.com/a/oilhHOg

**Comment by Jules-WinnfieldX** [comment]
> not sure if this issue is related to what i'm experiencing but here is what's been happening with cyberdrop-dl 2.20.5
> 
> when re-running the program used to be neaty when checking existing file, now it became much messier, which results spam in the command prompt on big threads and eventually it stops and doesn't finish the thread
> 
> this screenshot is how it used to check existing files (this screenshot was taken with 2.20.5 it sometimes works fine but most of the times not): https://imgur.com/a/1ks073c
> 
> and this is how it became messy and eventually gets stuck and stops: https://imgur.com/a/oilhHOg

2.20.5 has those lines as debug statements, which should only be going into the downloader.log file. You may have turned on a python debug mode or something,  But that's not default behavior for the program. It also would have nothing to do with the program becoming stuck as you put it. Please open a separate issue request and include your downloader.log file in it. I'll need it to tell you anything.

**Comment by Jules-WinnfieldX** [comment]
Closing as there was no response.
