### ISSUE TITLE
Downloader has problem with too long folder names?..

### ISSUE THREAD

**Issue by YoloBoomer** [Jules-WinnfieldX/CyberDropDownloader#16]
Link ~Redacted~
Failed to download the 5-th (or 4-th, I don't remember) file from there: just hang. I closed the window after approx. 2 minutes of waiting. The folder "Lera Himera Lara Croft in cosplay + swimsuit + robe + nude 1..." is unresponsive now (and why does it have "..." in its name in the first place?), I can't either access or delete it:
![Untitled](https://user-images.githubusercontent.com/85622926/121352952-a5f5e900-c92d-11eb-80e3-e05141e3a093.png)
At the same time, the script itself apparently can access the folder - I started it again and was able to finish downloading, however afterwards I received the same problem - the folder is unresponsive.

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/1.1.2

Give this a try, it's a temporary fix, but it works. The '...' is there because that's essentially what the web page is named. You can see it yourself in your web browser by mousing over the tab name. 

Forward thinking I should also add proper character validation for filenames/directory names.
