### ISSUE TITLE
[FEATURE] - Support 3rd party tool forking - e.g. Call megadown for mega.nz links

### ISSUE THREAD

**Issue by SethBodine** [Jules-WinnfieldX/CyberDropDownloader#173]
**Is your feature request related to a problem? Please describe.**
While built-in support for additional websites is ideal, it would be great to be able to be able to manage unsupported websites where 3rd party tools could be leveraged to download content.

**Describe the solution you'd like**
Custom conf file where a custom FQDN with corresponding command with arguments could be specified
e.g.
mega.nz=megadown %url%

**Comment by github-userx** [comment]
I think this would be a fantastic enhancement/feature. For mega.nz,I currently use megatools/megadl as well, but could be handy if you can feed these links directly to cyberdrop-dl.

But then again, I shouldn’t be that lazy. It’s not too much asked from me to use megatools separately. 

It also gets trickier since megadl has various commandline options available.

**Comment by Jules-WinnfieldX** [comment]
I've implemented support for sending unsupported links to JDownloader2, so I'm going to close this.
