### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by darkwind1q** [Jules-WinnfieldX/CyberDropDownloader#182]
I think there is a bug with how the downloader interact with downloader.log and downloader_history.sqlite

I am running the downloader following the "pip install method".
What is have encounter is that the downloader have missed a few files.
When the downloader finished it reported all file is downloaded, however, the files are missing. I have tried rerunning the downloader a few times but it keep reporting that all file is downloaded, but those files are still missing. So I check the downloader.log and it shown that the file have been downloaded.
I have tried uninstall and reinstall the downloader using "pip3 install/uninstall cyberdrop-dl" command with no changes.

I have ran a few tests by deleting some files in the folder that was created by the downloader. and rerun the downloader. The result is the downloader still spit out the download complete and every files is downloaded despite the deleted file still missing.

The way I finally got it to download every file correctly was using the "script method" to get a fresh download.

If what I suspect is right, the downloader is checking the downloader.log and downloader_history.sqlite file for a download history instead of the folder it created to see if the all the files are downloaded. So maybe having the downloader check the folder instead of the log and history file might help resolve this issue.

**Comment by Jules-WinnfieldX** [comment]
"I have ran a few tests by deleting some files in the folder that was created by the downloader. and rerun the downloader. The result is the downloader still spit out the download complete and every files is downloaded despite the deleted file still missing."

This is as intended. It was created this way so that when scraping content (like thotsbay threads), if you move content to a different drive, sorting structure, etc, the downloader won't redownload things you already have. You can use the --ignore-history flag when running to achieve what you want.
