### ISSUE TITLE
[FEATURE] GoFile KeepAlive

### ISSUE THREAD

**Issue by BrianJ20** [Jules-WinnfieldX/CyberDropDownloader#236]
Seeing as gofile deletes files after 10 days of no unique downloads, I think it could be useful if there was an argument, that would initiate download of a file while not completing it.  I've tested that this works by manually starting a download and immediately cancelling it.
This increases the download count by one and my test file is still alive after 3 weeks with only me grabbing it once a week.

I'm hoping this would enable people to have a list of their own GoFile uploads, that they could keep alive indefinitely.

An idea would be
`$ cyberdrop-dl -GoFileKeepAlive -i GoFileLinks.txt --ignore-history`

**Comment by wtfdeko** [comment]
can you help me with something? how to download from any link without images, i know the "--exclude-images" but can i use the code? is it in the "URL" file? help me

**Comment by github-userx** [comment]
I vote against this - as this would mean a direct abuse of gofiles‘ services which im thankful they still offer for free to everyone (unlimited filesize being one of the perks).

As a user/Downloader I know Your pain of seeing all the dead gofile links and gofile definitely has become stricter with their 10days enforcement but at the end of the day..if your file(s) are actually not accessed regularly, I think it’s fair for gofile to remove them. 

There are enough other hosts with longer retention than 10 days. Plus if you really more permanent storage you could always still get gofile premium (I’m sure they would even let you pay with crypto instead of patreon).

**Comment by Jules-WinnfieldX** [comment]
Agree with userx on this one, and it's arguably outside the scope of this tool. I'm going to close this.
