### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LuciferxR** [Jules-WinnfieldX/CyberDropDownloader#255]
hey i try to download but i faced this kind of error please tell me how to fix ASAP ?

hare is the screenshot 
![WindowsTerminal_JMxLNYPqw5](https://user-images.githubusercontent.com/99616672/200095132-fa411b51-7f45-4d67-b4d0-12bd0fe0320f.png)

**Comment by Jules-WinnfieldX** [comment]
Cyberdrop-dl is not a recognized internal command

This is most often caused by python not being included on path. Make sure you ticked the box for 'add python to path' during installation. (see above)


If that didn't work, follow what another user did:
I don't know if this will help anyone having my issue, but after 2 reinstalls of python with path selected I was still receiving cyberdrop-dl not recognized error. So I ran python -m pip list -v , in cmd to see where cyperdrop was like was mentioned a few pages back. Then I went to AppData\Roaming\Python\Python310\site-packages and I removed the 2 cyperdrop folders that were in there. I then opened cmd and ran pip3 install cyberdrop-dl. Now the scraper works for me.
