### ISSUE TITLE
Downloader repeatedly hangs at random files.

### ISSUE THREAD

**Issue by TokyoJedi** [Jules-WinnfieldX/CyberDropDownloader#27]
It seems to hang at random files throughout the process. It will be stuck on the previous message for hours.

**Comment by Jules-WinnfieldX** [comment]
The issue, as far as I can tell. Pertains to videos which take a long time to load and download. Especially when they you are connecting to specific (slow) servers. I plan on making improvements to this utility in order to have an active status of how downloads are proceeding (think progress bar based on size expected vs downloaded). But at the moment I can't fully recreate the issue, as the files do all end up proceeding. Let me know if there's more info you could give me.

**Comment by LenAnderson** [comment]
Happens a lot to me with images that are a couple of MB in size. Adding a timeout to `request.get` (see https://2.python-requests.org/en/master/user/advanced/#timeouts ) helps move things along. If that could be combined with "continuing" the download upon finding an incomplete (or "corrupt" as the log message from the downloader calls it) file instead of starting over that should really help on slow connections.  
Continuing incomplete downloads from CyberDrop should be possible, at least it is possible for Chrome when downloading manually.

**Comment by LenAnderson** [comment]
Added PR #29 for timeout and download resume.

**Comment by Jules-WinnfieldX** [comment]
Approved and merged LenAnderson's PR. New release to follow in a few.
