### ISSUE TITLE
[FEATURE] Simple Log of Failed/Incomplete Downloads

### ISSUE THREAD

**Issue by cam-au** [Jules-WinnfieldX/CyberDropDownloader#276]
**Is your feature request related to a problem? Please describe.**
When running a large batch, potentially across multiple hosting sites, often many downloads will time out or fail (Particularly with Anon, Bunkr and GoFile).
This would then provide a simple list for retrying.

**Describe the solution you'd like**
Separate txt file, similar to the downloader.log file but listing only 1 line per failed file, potentially generated at the end of the program running, and a simple description of what happened.
eg:
Partial: Timeout: https://cdn-128.anonfiles.com/blahblahblah1
Failed: Error message: Unexpectedly got text as response: https://cdn-128.anonfiles.com/blahblahblah2
Failed: Error Scraping: https://stream.bunkr.is/v/eg101010
Ideally this would generate a new file (timestamped for uniqueness?) each time it's needed rather than overwriting.

**Additional context**
Understand this would potentially require creating a database of sites supported, and error codes returned and then using that database as a lookup (happy to attempt to help/crowd source this piece).

**Comment by Jules-WinnfieldX** [comment]
The only issue I see with this, is that these links would be essentially completely useless for the program in a lot of cases, most of the scrapers aren't setup to handle direct download links. Above that, these links require cookies in order to download. 

In recent versions I've attempted to get around error 2 for example by re-scraping specific links if they hit certain responses.
