### ISSUE TITLE
[BUG] Running program doesn't do anything 

### ISSUE THREAD

**Issue by Kekerin0** [Jules-WinnfieldX/CyberDropDownloader#277]
**Describe the bug**
I ran Cyberdrop-DL last night and it gave me the message "There are partial downloads from this run, please re-run the program." and didn't seem to have downloaded any files after I checked the modified dates of all of the folders in Downloads. It gave the same error and had the same behavior the previous day when I ran it, but I didn't back up the downloader.log file like I did here. It looks like downloader.log is only the log of the last time you ran the program. I am currently running it again, but am doubtful that it will download anything based on these previous 2 runs.

**To Help Reproduce**
I'm not sure how to reproduce the behavior exactly. I moved a fully downloaded folder from another PC to this one and when I ran the program the first time, it seemed to be merging the databases; just detecting that files already exist and skipping them. I thought, okay, I will just run it again, and it will download some new stuff this time. It didn't. As you can see in downloader.log, my arguments at startup were --separate-posts and --include-id. And all the URLs I am trying to download from are coomer.party URLs.

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version 3.6.15
 -Python version 3.10.8

[12-4 downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10150032/12-4.downloader.log)

**Comment by Kekerin0** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10150688/downloader.log)
Same thing happened again, here's the log.

**Comment by Jules-WinnfieldX** [comment]
You are getting a "there are partial downloads message" because you have a file that didn't complete downloading. Specifically it looks like '4a9256d5-e93f-4318-9676-1e0b2708cd66.m4v' didn't finish. You'll find a '4a9256d5-e93f-4318-9676-1e0b2708cd66.m4v.part' file in one of the folders. The "from this run" only indicates that it is a partial download related to something that was scraped during the current run, it doesn't have to have downloaded any bytes during the run.

As for new things, there aren't any. You have downloaded everything else already.

**Comment by Kekerin0** [comment]
Should I delete the .part file and try again?

**Comment by Jules-WinnfieldX** [comment]
Yes
