### ISSUE TITLE
[FEATURE] Move Completed URLs from urls.txt to <completed_urls.txt>

### ISSUE THREAD

**Issue by MDKAOD** [Jules-WinnfieldX/CyberDropDownloader#522]
**Is your feature request related to a problem? Please describe.**
When the URL's file is bulky with arbitrary URL suffixes, it's difficult to correlate when a link has been completed (at it's current state) and if there are no further updates expected to a gallery, rather than keep the URLs in the URL.txt file, it would be great to offload that to a record of some kind that isn't parsed upon re-launch.

**Describe the solution you'd like**
A switch for when a URL is completed to move 'completed' urls to a specified output <completed_urls.txt> for example.

**Comment by Jules-WinnfieldX** [comment]
So that's kinda the thing right? 

"if there are no further updates expected to a gallery"

There is no way for CDL to be able to judge this, beyond that, There's not a realistic way for majority of links to be able to know if every file inside of them has actually been completed. We can guess, and assume everything we've done is correct, but there could be scraping errors for example and files were missed that might get picked up on subsequent runs. 

The URLs.txt file is meant to be entirely user curated. Anything given in it, the program will run with. The program doesn't write to that file, it won't exclude from that file (unless told to).

Direct links I can understand, links that usually end in a filename, and extension. However they take such little time and resources to scrape that it isn't worth attempting to exclude them from the programs perspective. It would also be weird to only do something with those links.

**Comment by MDKAOD** [comment]
Can we keep this conversation going? I understand what you're saying, and it makes sense. My thought is that while the url's file is user generated, it's difficult to manage when there's a list of url's like: 

`aby7sfg/`
`bnjs875n/`
`jk8dhh54/`
`8ji3bnfjh/`

And the program already handles "Completed" files (as best as it can). So if there's a way to take the knowledge of "completed" and even output to a "completed_urls" file, then we can diff the two files and maintain the URL's file manually. For example, we already have switches for --output-errored-urls and --output-unsupported-urls, perhaps we can get an --output-completed-urls

I'm using this from a _data hoarder_ point of view from bunkr, not forums. The cause of this ask is that I'm using a portable drive and have an overloaded URL's file. Once this disk fills up, I'll need to move some files around but then the program will just rescrape those urls and redownload them. And short of opening up every link in my url's file again and cross comparing, it's difficult to determine what's been scraped and what hasn't. 

I'll defer to your expertise on this, maybe there's another solution that already exists?

**Comment by MDKAOD** [comment]
AH! Okay then. I read through the documentation but I didn't put those pieces together. Thank you for the assistance. You've created a pretty elegant piece of software here. It does what it advertises and does it well.

**Comment by Jules-WinnfieldX** [comment]
No worries! I might still do a completed file in the future, but it's a niche issue, and it takes a fair bit of work to add a new file output like that
