### ISSUE TITLE
[BUG] The app closes itself after some time

### ISSUE THREAD

**Issue by MrxHellsing** [Jules-WinnfieldX/CyberDropDownloader#53]
**Describe the bug**
After some time, the app closes itself. It will download for about half an hour or maybe more, I haven't exactly counted.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. For example, I have started downloading a video album of 30 GB. I kept it on and after 20-30 mins, I noticed that the app wasn't on the taskbar nor was it running in the background and I didn't close it either, it closed itself!
2. Can't actually provide a screenshot of this as it literally closes itself.
3. Using the latest version 2.3.0

**Setup Information**
 - OS: [Windows 10 Pro 64 bit, 20H2, OS Build 19042.1526]
 - 2.3.0

**Additional Information
I was downloading from Bunkr.is

**Comment by Jules-WinnfieldX** [comment]
Try with 2.3.1. If it doesn't work, I'll need more info, which likely means I'll need the logs.log file after a failed run.

**Comment by MrxHellsing** [comment]
It closes on the new version as well. Attaching the log file.
https://drive.google.com/file/d/1EwBD1VV4ZXJyYju3BNBP2ZkJsWu9H5Ud/view?usp=sharing

**Comment by Jules-WinnfieldX** [comment]
So, not really intended behavior. But it is doing as designed. It's timing out (server issues, not downloader issues) and exceeding the maximum amount of tries allowed for an individual file (currently that is set at 10). I should make that user adjustable, and find a way for it to not close the program when that happens.

**Comment by MrxHellsing** [comment]
I found another error today. For some of the files, it downloaded portions and didn't download the rest but probably counted the whole thing as a completed download. Let's say a file is about 3GB+ large; it downloaded about 200MB but didn't download the rest.

**Comment by Jules-WinnfieldX** [comment]
If the file still exists as a .download file, that's also by design. That's a partial download that will continue to download as the script runs. If a download breaks (like with the above timeouts), we save the portion of the file we have, then restart the download from where it left off. Seeing as the program exits for you, it never has the chance to finish that download. Simply running the program again will also let it pick up from where it left off for that file assuming the link is still in urls.txt.

**Comment by Jules-WinnfieldX** [comment]
is the incomplete file still a .download file?

**Comment by Jules-WinnfieldX** [comment]
So, as it's hard to make downloads fail reliably, this is taking a bit to get right. It's coming though.

**Comment by Jules-WinnfieldX** [comment]
Give 2.3.2 a try
https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases

**Comment by MrxHellsing** [comment]
> is the incomplete file still a .download file?

No, it is a full mp4 file

**Comment by Jules-WinnfieldX** [comment]
I'd recommend just deleting the file and trying again with the new version.

**Comment by Jules-WinnfieldX** [comment]
Downloading multiple files at once has been how it is since version 2.0, prior to that there was an option to set the number of download workers but it automatically defaulted to however many CPU threads were available. I can add that option back in. each improvement or request should have their own issue created.

**Comment by Jules-WinnfieldX** [comment]
edited above comment to fix info.
