### ISSUE TITLE
[BUG] Unclosed connector error

### ISSUE THREAD

**Issue by woopnar** [Jules-WinnfieldX/CyberDropDownloader#554]
The last couple of days the downloader GUI is getting stuck, when I see the logs the last couple of lines are:

```
2023-08-17 19:40:21,929:ERROR:base_events:base_events.py:1729:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002707A272170>
```

Repeated like 19 times.

Before that I get a couple of Bunkrr errors like: 

```
2023-08-17 19:40:21,295:DEBUG:downloaders:downloaders.py:287:
https://media-files12.bunkr.la/539701643545944064-a3gDkL7x.mp4 (DDoS-Guard detected, unable to download)
2023-08-17 19:40:21,377:DEBUG:downloaders:downloaders.py:291:We ran into a 400 level error: CustomHTTPStatus.IM_A_TEAPOT
2023-08-17 19:40:21,382:DEBUG:base_functions:base_functions.py:60:Failed Download: 539701643545944064-a3gDkL7x.mp4
```
Then I have to ctrl+c my way out the program.

I've waited hours to see if something happens and nothing ever happens.

I'm running the latest versions, currently *4.2.186* on Windows 10.

I have a 660 lines URLs file, so its difficult to know what url is causing the issue.

**Comment by Jules-WinnfieldX** [comment]
Unclosed client connector can be ignored. It is usually caused by an actual error before those are printed. Or it happens after the program has completed.

As your bunkr error says, it can't download that file because of DDOS-Guard. 

I cannot help beyond this with the information provided. I would suggest making due until the rewrite releases (currently in progress)
