### ISSUE TITLE
Is it possible to download more than 2 files at once from Bunkr?

### ISSUE THREAD

**Issue by fruitvenison** [Jules-WinnfieldX/CyberDropDownloader#81]
I have had a look through settings.py but can't seem to find a way to increase the concurrent files downloading? Current it seems set to 2 maximum.

I cannot seem to get more than 1MB/s for download speeds either. I have 200/20 internet and have tested with and without a VPN.

**Comment by Jules-WinnfieldX** [comment]
It is limited to 2 downloads concurrently at Bunkr because that's what Bunkr has restricted it to. They only allow two simultaneous downloads at any given time. 

Download speed will also be dependent on server speed, and that of bunkr's has been slow the last few weeks as they've been working through migrations and transitions amongst other problems.

**Comment by Jules-WinnfieldX** [comment]
No worries! Appreciate it
