### ISSUE TITLE
[FEATURE] Default to username on untitled coomer

### ISSUE THREAD

**Issue by woopnar** [Jules-WinnfieldX/CyberDropDownloader#858]
Some coomer pages appear as Untitled when donwloaded. 

It would be a better solution to use the username when that happens.

Some models that appears as Untitled are brattykayla or your_submissive_doll.

Thanks.

**Comment by skil-issue** [comment]
Hey Jules; love the project, thanks for all your work on it. Reviving this issue because I've been having the same problem. Here's my log for a run I was doing just now. All the downloads from [this link](https://coomer.su/onlyfans/user/hannahowo) were going to the Untitled folder when I have an existing folder for this creator. 
It's worth noting that 
- this has been happening recently with other creators as well
- I can't pinpoint when it start or what common characteristic the creators have, it seems to be random as far as I can tell

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14768843/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
5.2.14 going up now that might fix it, but it'll probably error out more.

**Comment by skil-issue** [comment]
Just an update here for posterity but can confirm that 5.2.14 seems to have resolved the untitled folder issue. Been running it since you patched it a few days back.
