### ISSUE TITLE
[BUG] Hi boss, my multi-threaded download settings are invalid :<

### ISSUE THREAD

**Issue by CryCitty** [Jules-WinnfieldX/CyberDropDownloader#875]
max_simultaneous_downloads: 10
max_simultaneous_downloads_per_domain: 10
👆I increased the number of task threads :< But it doesn't seem to take effect
[URLs.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14910218/URLs.txt)

**Screenshots**
![2024-04-09 031252](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/56867945/09f16943-d2a0-417e-b069-bdd0aeff488a)

**Setup Information**
7950X3D 32G RAM
wondows11 23H3 22631.3374

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14910212/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Specific domains are hard coded to be limited to a certain number of simultaneous downloads. 

Currently these are: download_limits = {'bunkrr': 1, 'cyberdrop': 1, 'coomer': 2, 'cyberfile': 2, 'kemono': 2, "pixeldrain": 2}

Nothing you enter in the configs will change these, unless they are lower than these. 

They are set this way because of restrictions set by the websites, it's to avoid ratelimiting and failed downloads.
