### ISSUE TITLE
[BUG] invalid content

### ISSUE THREAD

**Issue by neuri48** [Jules-WinnfieldX/CyberDropDownloader#883]
getting alot of invalid content  errors on nudostar. 
this post isnt downloading and marked as a failed download
https://nudostar.com/forum/threads/victoria-justice.29871/post-1593029

**Comment by Jules-WinnfieldX** [comment]
Open the images in said post, they aren't direct links. And it's on a site that isn't explicitly supported by CDL. 

But because there is a file extension in the URL, CDL will try and download it. But instead it receives a webpage, which is invalid content, it's not image content. 

So round about way of saying, not a bug, it's intended behavior.

**Comment by neuri48** [comment]
ok that was a bad example lol. it also happens with this type of post 
https://nudostar.com/forum/threads/elsie-hewitt-elsie.1424/post-1451469

**Comment by Jules-WinnfieldX** [comment]
Can't comment on past versions, but at least on latest version, that post downloads as expected
